Patch for case insensitve Table filter search
firzok/react-offline-table pull request #2
Opened 2020-03-10 16:44 UTC by Faateh-Jarree

- Filter search now works with case insensitive input
- Removed extraneous for each loop

2020-03-10 17:38 UTC, firzok requested changes

2020-03-10 17:38 UTC, firzok commented on src/index.js
> +    const filterText = e.target.value;
I think its better to lowercase filterText once here instead of having to do it everywhere.

2020-04-04 06:23 UTC, Faateh-Jarree commented
ive merged the latest changes into the pull request.

2020-04-04 14:47 UTC, firzok approved these changes

2020-04-04 14:47 UTC, merged